title: ISV Playbook
description: ISV Playbook India
theme: just-the-docs

url: https://isvplaybook.github.io/isvplaybook/

aux_links:
  Template Repository: https://github.com/isvplaybook/isvpb3

nav_enabled: true
heading_anchors: true
